### ISSUE TITLE
Parameter sets for ML methods

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#12]
@yanxon 
I have resolved the conflicts. Please update your repo.

For the next step, please implement three sets of ml parameters as we discussed.
say
-`light`
-`medium`
-`tight`

**Comment by yanxon** [comment]
Implemented

**Comment by qzhu2017** [comment]
@yanxon 
For the light set, 
```
            grid = {'light': {"est__learning_rate": [0.1], "est__n_estimators": [1000], "fs__threshold": [0.0]}, 
```
Does these algorithm provide default parameters. I thought it is better to use those default parameters, instead of using some arbitrary parameters defined by ourselves.

**Comment by qzhu2017** [comment]
@yanxon 
It is also good to store these parameter sets in a separate file, instead of inserting them to method.py

I suggest we create a single file called default_sets (.yaml or .json) for algos. 
yaml seems to be good option for this.

**Comment by yanxon** [comment]
![image](https://user-images.githubusercontent.com/32254481/47174005-608bd580-d2c4-11e8-96d1-b5c1e3f6c7ba.png)

**Comment by qzhu2017** [comment]
@yanxon  I have updated my plan regarding the rough idea of ML pipes and the definition of three sets of parameters. See the most recent README.md

**Comment by qzhu2017** [comment]
```python
            self.read_dict()
            if self.level in self.parameters_level:
                self.SGD_grid = grid[self.level]
            else:
                self.SGD_grid = self.dict
            search = GridSearchCV(SGDRegressor(tol = 1e-5), param_grid = self.SGD_grid, cv=10)
            search.fit(self.X_train,self.Y_train)

            best_penalty = search.best_params_['penalty']
            best_alpha = search.best_params_['alpha']
            best_learning_rate = search.best_params_['learning_rate']

            best_estimator = SGDRegressor(tol = 1e-5, penalty = best_penalty, alpha = best_alpha, learning_rate = best_learning_rate)
```

Looks like you are using this scheme for every algo. Why not make it more universal?
There should be a universal way to do so.

Besides: tol = 1e-5, cv=10 should go to yaml file. We should put all parameters to yaml file.

**Comment by yanxon** [comment]
@qzhu2017 

Hi, I fix the parameter sets in the method.py as described in the plan.

Please review it. If there's something else that needed to be fix, please put "the card" back to progress.
