### ISSUE TITLE
[Plan] Add a step of feature selection in ML pipeline

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#15]
Currently, we have only a relative small array of descriptors, compared to the database. However, there may be a case we have more descriptors than the materials data. In this case, it would be good add a step of feature selection as part of a pipeline.

```python
clf = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1"))),
  ('classification', RandomForestClassifier())
])
clf.fit(X, y)
```

Something needs to be done in future.

**Comment by yanxon** [comment]
PCA and VarianceThreshold are implemented through  pipeline.

**Comment by qzhu2017** [comment]
Good. Could you please update the ReadME.md as well? explain a bit on this functionality

**Comment by qzhu2017** [comment]
```
qzhu@cms:/scratch/qzhu/github/PyXtal_ml$ python main.py 
/opt/python-3.6.5/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    runner = run(N_sample=N_sample, jsonfile=jsonfile, level=level, feature=feature, pipeline = pipeline)
TypeError: __init__() got an unexpected keyword argument 'pipeline'
```

@yanxon did you run the test on main.py?

**Comment by yanxon** [comment]
@qzhu2017 

I will update the ReadMe.md with more description for the functionality.

Sorry about that. I ran the test on main.py just fine. I forgot to push the run.py file. It should be working now.

**Comment by qzhu2017** [comment]
@yanxon , is this what you want to call pipeline in main.py? see my update 222434c

**Comment by yanxon** [comment]
Yes. pipeline = 'PCA' or 'VarianceThreshold'. It is False in default.

**Comment by yanxon** [comment]
I just updated the Readme.md to include pipeline for in ml folder.
