### ISSUE TITLE
[call for volunteers] Project function in GitHub

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#16]
I am thinking it is good to use the project function in GitHub to optimize our development.
Can any of you have a look and set a template for our project?

https://help.github.com/articles/about-project-boards/

**Comment by yanxon** [comment]
Can you checkout the project?

**Comment by qzhu2017** [comment]
looks great

**Comment by qzhu2017** [comment]
@David-Zagaceta  Please also list your project todo list and give your planned timeline there.

**Comment by qzhu2017** [comment]
Done.
