### ISSUE TITLE
yaml file readability

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_ml#17]
I would like to improve the readability in yaml file

**Comment by qzhu2017** [comment]
@yanxon 
Please follow the way as described in the [README.md](https://github.com/qzhu2017/ML-Materials/blob/master/ml/README.md').

Ideally, the yaml file should give the default parameters for each algorithm, grid search options.

For the code in method.py,
I suggest you include all steps,
- split the data to training and test sets
- choose the estimator 
- grid search
- process the features
- fit and predict
- cross validation

This way, we can call the ML method more conveniently without going to the details of each algorithm.

**Comment by yanxon** [comment]
@qzhu2017 

The GridSearchCV automatically does cross validation + fit for us.

Please review method.py, I will add more ml algorithm once the structure is ok. Unless, I have to change a lot if the structure is not optimized.

Here is the list of I change:
1. 'light' doesn't have any parameters. It uses the default parameters defined by scikit-learn.
2. 'medium' doesn't have any parameters either. It uses the default parameters defined by scikit-learn and perform cross validation through GridSearchCV.
3. 'tight' have parameters which is defined in the yaml file.

The params in yaml file is for 'tight' only. Also, I defined 'cv' for K-fold cross validation.

I don't understand "process the features." Can you please explain?

We can use sklearn.model_selection.RandomizedSearchCV if GridSearchCV takes very loooong.

Howard

**Comment by qzhu2017** [comment]
@yanxon I am not sure if grid search does the cross validation for us.
By cross validation, I mean to split the data to train set and test set many times. As such, we ensure that the model does not rely on the split of data.

**Comment by qzhu2017** [comment]
@yanxon also, please rename the file to .yaml, instead of yml

**Comment by yanxon** [comment]
The grid search does K-Fold cross validation for us. Thus, the name is GridSearchCV.

For example, you have this parameters n_estimators = [1,2,3,4,5], leaf_size = [1,2,3,4,5], cv = 10. GridSearchCV actually does 5 x 5 x 10 = 250 calculations.

Please check out https://www.youtube.com/watch?v=Gol_qOgRqfA

**Comment by yanxon** [comment]
I changed to .yaml.

**Comment by David-Zagaceta** [comment]
@yanxon 

After the most recent commit I'm getting an error in main

cms$ python main.py
/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ml.method import method
  File "/homes/davidz87/ML-Materials/ml/method.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by qzhu2017** [comment]
For the current stage, the yaml file looks good. 

However, I am not quite sure about the use of cv in GridsearchCV function. 

If we use cv=10, it will explore the calculations for 10 times. Do you have the output of r^2 or MAE for each calculation. I suggest we don't just select only the best results from 10 calculations. We also need to provide some information about the variation of these r2/mae values. They can tell us if we can trust these ML models constructed by the medium set.

**Comment by yanxon** [comment]
Sounds good. I will implement that feature.

**Comment by yanxon** [comment]
I'm sure it output the r2 results for each CV calculation.
