### ISSUE TITLE
[Alert] Please test the main.py when your implement the new methods 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#19]
@David-Zagaceta @yanxon 
our main.py is the universal test script. Please modify and run this script every time after you make any changes! This should not take long time. But it will quickly help you to find the bugs.

**Comment by yanxon** [comment]
![image](https://user-images.githubusercontent.com/32254481/47252963-caf66000-d401-11e8-9cb6-bb12f33c82a7.png)

**Comment by qzhu2017** [comment]
I have updated the main file to make it easier to use.
