### ISSUE TITLE
[Question] How to export the pre-trained model?

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#23]
Can anyone investigate how to export the pre-trained model. I wonder if we can save the ml model trained from the calculation and then use it as an executable to directly call it to calculate any arbitrary crystal structure.

**Comment by David-Zagaceta** [comment]
from sklearn.externals import joblib
joblib.dump(model_name, 'filename.joblib') # save the model
model = joblib.load('filename.joblib')

**Comment by David-Zagaceta** [comment]
There are some security concerns regarding this, namely, the saved files cannot be scanned so keep our saved models internal.

**Comment by qzhu2017** [comment]
added the option in 9bdb313
