### ISSUE TITLE
[Announcement] Update you local repo

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#24]
Dear All,

I have just managed to make this library installable via setup.py. I also renamed the library as `PyXtal_ml`.

This is gonna be a new stage of our development. For your convenience, I suggest you update your repo via.
```
git clone https://github.com/qzhu2017/PyXtal_ml.git
```
From now on, please ignore the previous copy, and implement your code based on the new local copy.

Please follow the instructions below to commit your code.
```
$ git pull
$ python setup.py install
$ python main.py
```
This will make sure that you get the latest copy and run it without any problem.
Before commit your code:
```
$ python setup.py install
$ python main.py
```
This will make sure you can run the modified code without any problem.

To commit your code
```
$ git status  # check if you have any changes
$ git add `the file you want to change`
$ git push 
```

When you want to import the functions from PyXtal_ml,
please use such statements.
```python
from pyxtal_ml.descriptors.descriptors import descriptor
```

**Comment by yanxon** [comment]
If I understand it correctly, by doing

`$ python setup.py install` 

You install pyxtal_ml in your local python pkgs. Is this accurate?

**Comment by qzhu2017** [comment]
yes, you do install to include PyXtal_ml as your local pkgs.
