### ISSUE TITLE
[Alert] Voronoi isn't working with the main code yet.

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_ml#29]
ML learning with GradientBoosting algorithm
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   100
Number of features:                 1344
Algorithm:              GradientBoosting
Feature:            Chem+RDF+ADF+Charge+Packing_efficiency+Volume_stats+Bond_stats+Coord_number+Chemical_ordering
Property:               formation_energy
r^2:                             -0.1959
MAE:                              0.8273
Mean train_score:                 1.0000
Std train_score:                  0.0000

ML learning with GradientBoosting algorithm
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   100
Number of features:                 1344
Algorithm:              GradientBoosting
Feature:             Chem+RDF+ADF+Charge
Property:               formation_energy
r^2:                             -0.0926
MAE:                              0.7997
Mean train_score:                 1.0000
Std train_score:                  0.0000

**Despite adding features, the number of features is still 1344.**

**Comment by yanxon** [comment]
ML learning with GradientBoosting algorithm
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   100
Number of features:                 1383
Algorithm:              GradientBoosting
Feature:            Chem+RDF+ADF+Charge+Voronoi
Property:               formation_energy
r^2:                              0.1430
MAE:                              0.6985
Mean train_score:                 1.0000
Std train_score:                  0.0000

**Nevermind. The descriptors are named 'Voronoi' instead of Packing_efficiency+Volume_stats+Bond_stats+Coord_number+Chemical_ordering.**

**Comment by qzhu2017** [comment]
I think the current way of using 'Voronoi' is better.
