### ISSUE TITLE
[Plan] add Multiprocessing 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#31]
In order to speed up the calculation, I think the most important thing is to add Multiprocessing in our descriptor calculation.
We need to run the following code in parallel 

```python
    def convert_data_1D(self):
        """
        convert the structures to descriptors in the format of 1D array
        """
        start = time()
        print('Calculating the descriptors for {:} materials'.format(len(self.strucs)))
        pbar = ProgressBar()
        feas = []
        for struc in pbar(self.strucs):
            try:
                feas.append(descriptor(struc, self.feature0))
            except:
                feas.append([])
                print('Problem occurs in {}'.format(struc.formula))
        end = time()
        self.time['convert_data'] = end-start

        self.features = feas
```
The best way is to include it multiple process function.
https://docs.python.org/3.6/library/multiprocessing.html

@David-Zagaceta @yanxon  Can you look into this?

**Comment by David-Zagaceta** [comment]
@qzhu2017 

I think we can implement multiprocessing using numba, specifically the prange function and precompiling parts of the main.

**Comment by qzhu2017** [comment]
@David-Zagaceta The best way is to use multprocess. It is very easy I guess. 

If you do it with numba, I guess the most important part is to rewrite the voronoi function, instead of using the function in pymatgen. I don't recommend it.

**Comment by David-Zagaceta** [comment]
@qzhu2017 

Alright.  I will use the multiprocessing implementation.  I will start work on that tomorrow morning.

**Comment by qzhu2017** [comment]
Done in run.py. 
```python
runner.convert_data_1D(parallel=2) #choose cpu number if you want to active this function
```
