### ISSUE TITLE
[Bug] main.py is not working

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#37]
It looks like main.py is no longer working.

Also, I found that the code complains when I increased the N_sample from 300 to 800 in torch_main.py

**Comment by yanxon** [comment]
@qzhu2017 

Sorry just for the late reply.

The main.py is no longer working because I had to change some of the algorithm architecture to support PyTorch and ScikitLearn.

Although for PyTorch is not full working yet. It is running, but I don't why it gives such a huge error (NaN). I will improve it. Nevertheless, in [torch_main.py](https://github.com/qzhu2017/PyXtal_ml/blob/master/torch_main.py) should perform ml_scikitlearn like normal.

N_sample for 800 should be working.

**Comment by qzhu2017** [comment]
It is a bit messy now. How can I do the following?
1, choose ANN from SKlearn and do ML for 1000 data
2, choose ANN from Pytorch and do ML for 1000 data

I want to do some test run and want to make sure we really understand the use of pytorch and the results are consistent.

I just tried to use pytorch from torch_main.py. It did not work.
```
qiangzhu@Qiangs-MacBook-Pro:~/Desktop/github/PyXtal_ml$ python torch_main.py 
/Users/qiangzhu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
run: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 512.55it/s]

ML learning with ANN algorithm
Traceback (most recent call last):
  File "torch_main.py", line 27, in <module>
    runner.ml_train(algo=algorithm)
  File "/Users/qiangzhu/Desktop/github/PyXtal_ml/pyxtal_ml/run.py", line 176, in ml_train
    ml.print_summary()
UnboundLocalError: local variable 'ml' referenced before assignment
```

**Comment by yanxon** [comment]
Can you please show me the torch_main.py?

I would you this script to run PyTorch:
```
from pyxtal_ml.run import run
from pkg_resources import resource_filename

# Please define your values in here, option 1, and option 2.
jsonfile = resource_filename("pyxtal_ml", "datasets/nonmetal_MP_8049.json")
feature = 'Chem'
feature_scaling = 'MinMaxScaler'
prop = 'formation_energy'
N_sample = 300
library = 'PyTorch' # SkLearn
algorithm = 'dl' # or dl

# Option 1: If you want to use an algorithm from Scikit-learn, please enter the following
level = 'light'
pipeline = False

# Option 2: If you want to use an algorithm from PyTorch, please enter the following
hidden_layers = {"n_layers": 3, "n_neurons": [50]}

# Running the user-defined values. Don't tresspass beyond this point.
runner = run(jsonfile=jsonfile, feature=feature, prop=prop, N_sample=N_sample, library=library,
            algo=algorithm, feature_scaling=feature_scaling, level=level, 
            pipeline=pipeline, hidden_layers=hidden_layers)
runner.load_data()
runner.convert_data_1D() #choose cpu number if you want to active this function
runner.choose_feature(keys=feature) #choose feature combinations if you want
runner.ml_train(algo=algorithm)
runner.print_time()
```

Basically, you have to choose between PyTorch or SkLearn in the library option. I haven't implemented this in one run: 
1, choose ANN from SKlearn and do ML for 1000 data
2, choose ANN from Pytorch and do ML for 1000 data

But, they can be done separately for now. I will fix them to run in one go.

**Comment by qzhu2017** [comment]
Okay, I guess I called pytorch instead of PyTorch.

But why the ANN training of pytorch is much worse than ANN from sklearn?
```
ML learning with ANN algorithm
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   300
Number of features:                  438
Algorithm:                       PyTorch
Feature:                            Chem
Property:               formation_energy
r^2:                             -0.0460
MAE:                              0.7516
load_data                   0.68 seconds
convert_data                0.59 seconds
ml                          1.62 seconds
```


```
ML learning with ANN algorithm
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   300
Number of features:                  438
Algorithm:                  MLPRegressor
Feature:                            Chem
Property:               formation_energy
r^2:                              0.7273
MAE:                              0.3339
Parameters: {}
Mean train_score:                 0.9237
Std train_score:                  0.0117
load_data                   0.69 seconds
convert_data                0.64 seconds
ml                          1.04 seconds
```

**Comment by yanxon** [comment]
@qzhu2017 

I can't figure that out yet. I ran with N_sample = 8000, and it's not getting any better.

I thought it was because of we need to do feature scaling. But that wasn't the case either.

Let me improve the pytorch.

**Comment by qzhu2017** [comment]
I think I fixed this issue.
In order to make it easier to understand how the code works.
I suggest add two options.
1, show the progress of learning (verbose=True) in sklearn
2, show the parameters used (estimator.get_all_params in sklearn)

**Comment by yanxon** [comment]
Hi,

That is great! I can't figure it out despite tweaking it all day yesterday.

Can you please tell me what's the issue?
