### ISSUE TITLE
What is the use of this line?

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_ml#38]
https://github.com/qzhu2017/PyXtal_ml/blob/733ecdfdb97149b9de469ae8f62c0020c0b8196c/pyxtal_ml/ml/dl_pytorch.py#L141

I think this is a typo, isn't it?

**Comment by qzhu2017** [comment]
I copied it from the pytorch doc.

**Comment by yanxon** [comment]
I don't think it's necessary because its equivalent to ReLU function. Deleting this line actually improve the result.
