### ISSUE TITLE
Is there a reason why you add _?

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_ml#39]
@David-Zagaceta 

https://github.com/qzhu2017/PyXtal_ml/blob/173cdb951a09dff40d857397d79a51a35f84d435/pyxtal_ml/descriptors/voronoi_descriptors.py#L72

**Comment by David-Zagaceta** [comment]
@yanxon 
I use _ as a prefix before a method or attribute name to mark the attribute/method inaccessible by other classes in the python interpreter.  For example, if you called dir(voronoi_descriptors), the attributes and methods with _ before the name would not show up.

**Comment by David-Zagaceta** [comment]
@yanxon 

Here's a good explanation.

https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc

**Comment by yanxon** [comment]
I see. Thank you, @David-Zagaceta .
