### ISSUE TITLE
A package design

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#4]
@David-Zagaceta 
@yanxon 
I have completed the class design for dataset and descriptors.
Now we need to add ML as well

The ultimate goal is that we can just use one script `main.py` to complete the following 
1, choose the data set and specify the target from property (`Y`)
2, compute the descriptor for the structure set (`X`)
3, perform machine learning for `X/Y` 

@yanxon 
1, Try to follow the way I did to create a method.py file in `ml/` to 
2, Please complete the ML part in `main.py` to call different ml methods.

@David-Zagaceta , you can start to think about implementing new descriptors, by following the way I did for `ADF.py`, `RDF.py`, `Chem.py`

After this is done, we can make it as a python package via `setup.py`

**Comment by David-Zagaceta** [comment]
Dihedral angle is implemented, I will start to think of other structural descriptors to implement.

**Comment by yanxon** [comment]
I don't see method.py in the ml directory. Do you mean KNN.py?

**Comment by yanxon** [comment]
I see. Do you mean like descriptor.py, but for all ML algo?

**Comment by qzhu2017** [comment]
@yanxon See the new 
https://github.com/qzhu2017/ML-Materials/blob/master/README.md

**Comment by qzhu2017** [comment]
I have put this to README.md
