### ISSUE TITLE
Charge.py

### ISSUE THREAD

**Issue by David-Zagaceta** [qzhu2017/PyXtal_ml#5]
@David-Zagaceta needs to implement charge.py in the same essence as chem.py

**Comment by qzhu2017** [comment]
@David-Zagaceta  please complete it asap

**Comment by qzhu2017** [comment]
@David-Zagaceta Please check if the json file for charge covers all elements. Otherwise, you need to do to something like the following:
```python
    def get_descrp_arr(self, elm):
        arr = []
        # the current json file has only 82 elements, some are missing
        if elm in ['Pa','Ac','Pu','Np','Am','Bk','Cf','Cm','Es','Fm','Lr','Md','No']: 
            elm = 'Th' 
        elif elm in ['Eu','Pm']:
            elm = 'La' 
        elif elm in ['Xe','Rn']:
            elm = 'Kr'
        elif elm in ['At']:
            elm = 'I'
        elif elm in ['Fr']:
            elm = 'Cs'
        elif elm in ['Ra']:
            elm = 'Ba'
        d = ele_data[elm]
        arr = []
        for k, v in d.items():
            arr.append(v)
        arr = np.array(arr).astype(float)
        return arr
```

**Comment by qzhu2017** [comment]
@David-Zagaceta 
please update the `descriptor.py` as well when you implement the new descriptor.

**Comment by qzhu2017** [comment]
@David-Zagaceta  it is better to move the statements of reading files outside. We don't want to open/close the file for many times.
check my chem.py
```python
    def get_chgdescrp_arr(self, elm=''):
        arr = []
        try:
            f = open(filename, 'r')
            emdat = json.load(f)
            f.close()
            arr = emdat[elm][0][1]
        except:
            pass
```

**Comment by qzhu2017** [comment]
Please run python main.py whenever you implement something new.
Here is the reason why I post the above issue.

If I just run RDF+Chem, it took 3.6 secs.
```
Total number of materials: 200
The chosen feature is: RDF+Chem
0 materials have been processed
Time elapsed for creating the descriptors: 3.627 seconds
```

If I run RDF+Chem+Charge.
```
Time elapsed for reading the json files: 0.597 seconds
Total number of materials: 200
The chosen feature is: RDF+Chem+Charge
0 materials have been processed
Time elapsed for creating the descriptors: 13.810 seconds
```

**Comment by David-Zagaceta** [comment]
@qzhu2017 

I reformatted charge.py to only open the file once.  There was no need to implement replacement values from other elements.  Element_charge.json covered all elements up to 95

**Comment by qzhu2017** [comment]
@David-Zagaceta did you run the test script?
```
qiangzhu@u-10-240-0-89:~/Desktop/github/ML-Materials/descriptors$ python charge.py -c POSCAR-NaCl 
Traceback (most recent call last):
  File "charge.py", line 47, in <module>
    charge = Charge(test)
  File "charge.py", line 20, in __init__
    des = self.get_chgdescrp_arr(k)
  File "charge.py", line 27, in get_chgdescrp_arr
    for k, v in d.items():
AttributeError: 'list' object has no attribute 'items'

```

**Comment by qzhu2017** [comment]
Please make sure your script works when you implemente any changes

**Comment by qzhu2017** [comment]
@David-Zagaceta As I told you, please make sure your script works when you implemente any changes!

If you add charge into main.py, and run it, you will quickly find that there is something with your charge. For a crystal with two types of elements, your charge returns a two columns of array!

**Comment by David-Zagaceta** [comment]
$ python main.py
C:\Users\david\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Time elapsed for reading the json files: 1.059 seconds
Total number of materials: 200
The chosen feature is: Charge
0 materials have been processed
Time elapsed for creating the descriptors: 0.142 seconds
Each material has 756 descriptors
Time elapsed for machine learning: 1.823 seconds
----------------------------------------
-------------SUMMARY of ML--------------
----------------------------------------
Number of samples:                   200
Number of features:                  756
Algorithm:                           KNN
Feature:                          Charge
Property:               formation_energy
r^2:                             -0.1855
MAE:                              0.7936

**Comment by qzhu2017** [comment]
It looks good now.
