### ISSUE TITLE
first complete test

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#8]
@yanxon 

I have implemented all parts to make the code run as follows.
```
$ python main.py
```

However, the ML is very poor. Below is an example which I got for band_gap
```
Time elapsed for reading the json files: 3.005 seconds
Total number of materials: 8049
The chosen feature is: RDF+Chem
Time elapsed for creating the descriptors: 267.185 seconds
Each material has 498 descriptors
Time elapsed for machine learning: 3.926 seconds
```

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/29445366/46994207-57361980-d0c8-11e8-9e02-22e87d86b925.png">

Please try to repeat the calculation, and tell me what's wrong with it.

**Comment by yanxon** [comment]
I assume the ML is poor because you have to optimize the parameters such as alpha and gamma for KRR; in this case, we have to do GridSearchCV. I have GridSearchCV in the ML.py code. I will integrate method.py and ML.py.

**Comment by qzhu2017** [comment]
@yanxon  Okay, please try to optimize the parameters for KRR and KNN with the parameters defined in `main.py`

I will focus on generating another set of data from Jarvis.

**Comment by qzhu2017** [comment]
Somehow the GradientBoostingRegressor() and pipe function yields very strong correlation. Need to figure out the reason. I haven't updated the code to the git repo
```python
 33         elif self.algo == 'GBR':
 34             est = GradientBoostingRegressor()
 35             pipe=Pipeline([ ("fs", VarianceThreshold()),("est", est)])
 36             pipe.fit(self.X, self.Y)
 37             self.y_predicted = pipe.predict(X_test)
 38             self.y_predicted0 = pipe.predict(X_train)
 39             print(pipe)
```
<img width="920" alt="image" src="https://user-images.githubusercontent.com/29445366/47002304-7f7e4200-d0e1-11e8-9ac6-877ac4a02ad1.png">

**Comment by qzhu2017** [comment]
@yanxon please be aware that your recent commit leads to several conflicts in some .py files. I will resolve it after you are done with it. But please don't do it next time.

**Comment by qzhu2017** [comment]
Howard and I have implemented the ML algorithm. It is working properly now.
